# Generated by Django 3.2.7 on 2021-12-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_products_cata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cata',
            options={'ordering': ('name',), 'verbose_name': 'Cata', 'verbose_name_plural': 'catas'},
        ),
    ]
