# Generated by Django 3.2.7 on 2021-12-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cata',
            options={'ordering': ('name',), 'verbose_name': 'Cata', 'verbose_name_plural': 'category'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='ava',
            new_name='available',
        ),
    ]
