# Generated by Django 3.2.7 on 2021-12-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211216_1749'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cata',
            new_name='categ',
        ),
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': ('name',), 'verbose_name': 'categ', 'verbose_name_plural': 'category'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='cata',
            new_name='catego',
        ),
    ]
