# Generated by Django 3.2.7 on 2021-12-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartid', models.CharField(max_length=250, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
