# Generated by Django 3.2.7 on 2022-01-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220104_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='cartlist',
            new_name='cart_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cartid',
            field=models.IntegerField(max_length=250, unique=True),
        ),
        migrations.AlterModelTable(
            name='items',
            table='cart_item',
        ),
    ]
