# Generated by Django 3.2.7 on 2022-01-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_cartid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cartlist',
        ),
        migrations.RenameField(
            model_name='cartlist',
            old_name='cartid',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='q',
            new_name='quan',
        ),
    ]
