# Generated by Django 3.2.7 on 2022-01-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20220106_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='prodt',
            new_name='prod',
        ),
    ]
