# Generated by Django 3.2.7 on 2022-01-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_prodt_items_prod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='prod',
            new_name='prodt',
        ),
    ]
