# Generated by Django 3.2.7 on 2022-01-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_rename_prod_items_prodt'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='items',
            table=None,
        ),
    ]
